var mySkills = '<div class="progress-container progress-success">'
+'<span class="progress-badge">HTML</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">'
+'<span class="progress-value">80%</span></div></div></div>'
+'<div class="progress-container progress-success">'
+'<span class="progress-badge">CSS</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">'
+'<span class="progress-value">60%</span></div></div></div>'
+'<div class="progress-container progress-success">'
+'<span class="progress-badge">PYTHON</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">'
+'<span class="progress-value">50%</span></div></div></div>'
+'<div class="progress-container progress-success">'
+'<span class="progress-badge">JAVASCRIPT</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">'
+'<span class="progress-value">20%</span></div></div></div>'
+'<div class="progress-container progress-success">'
+'<span class="progress-badge">PHP</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">'
+'<span class="progress-value">30%</span></div></div></div>'
+'<div class="progress-container progress-success">'
+'<span class="progress-badge">MAEN PRIPAYER</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">'
+'<span class="progress-value">90%</span></div></div></div>'
+'<div class="progress-container progress-success">'
+'<span class="progress-badge">WEB PENTEST</span><div class="progress">'
+'<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">'
+'<span class="progress-value">20%</span></div></div></div>';
var project = '<div class="card-body" id="tukangNyepam">'
+'<h4 class="card-title mb-2">Tukang Nyepam <span class="badge badge-success float-right mt-1">v2</span></h4>'
+'<hr class="line-success my-1 w-50">'
+'<p class="card-text mt-1">Sebuah tool haram yg berfungsi untuk mengirim spam kepada hp seseorang.</p>'
+'<a href="#tukangNyepam" data-toggle="tooltip" title="Sedang dalam pengembangan, silahkan hubungi Admin" class="btn btn-simple btn-success">Coba</a>'
+'</div>'
+'<div class="card-body" id="twibbonJagoan">'
+'<h4 class="card-title mb-2">Twibbon Jagoan <span class="badge badge-danger float-right mt-1">v2</span></h4>'
+'<hr class="line-danger my-1 w-50">'
+'<p class="card-text mt-1">Tool untuk pasang Twibon Asosiasi Bang Jago Nusantara, hanya untuk kaum Jagoan.</p>'
+'<a href="#twibbonJagoan" data-toggle="tooltip" title="Sedang dalam pengembangan, silahkan hubungi Admin" class="btn btn-simple btn-danger">Coba</a>'
+'</div>'
+'<div class="card-body" id="fakeMailer">'
+'<h4 class="card-title mb-2">Fake Mailer <span class="badge badge-primary float-right mt-1">v4</span></h4>'
+'<hr class="line-primary my-1 w-50">'
+'<p class="card-text mt-1">Pasti U know lah email spoofing itu apa.</p>'
+'<a href="#fakeMailer" data-toggle="tooltip" title="Sedang dalam pengembangan, silahkan hubungi Admin" class="btn btn-simple btn-primary">Coba</a>'
+'</div>';
document.getElementById('aingNoob').innerHTML += mySkills ;
document.getElementById('project').innerHTML += project ;
